/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AnimalBase } from './models/AnimalBase';
export type { AnimalBaseResponse } from './models/AnimalBaseResponse';
export type { AnimalFull } from './models/AnimalFull';
export type { AnimalFullResponse } from './models/AnimalFullResponse';
export type { AnimalHeader } from './models/AnimalHeader';
export type { AnimalSearchCriteria } from './models/AnimalSearchCriteria';
export type { AstronomicalObjectBase } from './models/AstronomicalObjectBase';
export type { AstronomicalObjectBaseResponse } from './models/AstronomicalObjectBaseResponse';
export type { AstronomicalObjectFull } from './models/AstronomicalObjectFull';
export type { AstronomicalObjectFullResponse } from './models/AstronomicalObjectFullResponse';
export type { AstronomicalObjectHeader } from './models/AstronomicalObjectHeader';
export { AstronomicalObjectType } from './models/AstronomicalObjectType';
export type { AstronomicalObjectV2Base } from './models/AstronomicalObjectV2Base';
export type { AstronomicalObjectV2BaseResponse } from './models/AstronomicalObjectV2BaseResponse';
export type { AstronomicalObjectV2Full } from './models/AstronomicalObjectV2Full';
export type { AstronomicalObjectV2FullResponse } from './models/AstronomicalObjectV2FullResponse';
export type { AstronomicalObjectV2SearchCriteria } from './models/AstronomicalObjectV2SearchCriteria';
export { AstronomicalObjectV2Type } from './models/AstronomicalObjectV2Type';
export { BloodType } from './models/BloodType';
export type { BookBase } from './models/BookBase';
export type { BookBaseResponse } from './models/BookBaseResponse';
export type { BookCollectionBase } from './models/BookCollectionBase';
export type { BookCollectionBaseResponse } from './models/BookCollectionBaseResponse';
export type { BookCollectionFull } from './models/BookCollectionFull';
export type { BookCollectionFullResponse } from './models/BookCollectionFullResponse';
export type { BookCollectionHeader } from './models/BookCollectionHeader';
export type { BookCollectionSearchCriteria } from './models/BookCollectionSearchCriteria';
export type { BookFull } from './models/BookFull';
export type { BookFullResponse } from './models/BookFullResponse';
export type { BookHeader } from './models/BookHeader';
export type { BookSeriesBase } from './models/BookSeriesBase';
export type { BookSeriesBaseResponse } from './models/BookSeriesBaseResponse';
export type { BookSeriesFull } from './models/BookSeriesFull';
export type { BookSeriesFullResponse } from './models/BookSeriesFullResponse';
export type { BookSeriesHeader } from './models/BookSeriesHeader';
export type { BookSeriesSearchCriteria } from './models/BookSeriesSearchCriteria';
export type { BookV2Base } from './models/BookV2Base';
export type { BookV2BaseResponse } from './models/BookV2BaseResponse';
export type { BookV2Full } from './models/BookV2Full';
export type { BookV2FullResponse } from './models/BookV2FullResponse';
export type { BookV2SearchCriteria } from './models/BookV2SearchCriteria';
export type { CharacterBase } from './models/CharacterBase';
export type { CharacterBaseResponse } from './models/CharacterBaseResponse';
export type { CharacterFull } from './models/CharacterFull';
export type { CharacterFullResponse } from './models/CharacterFullResponse';
export type { CharacterHeader } from './models/CharacterHeader';
export type { CharacterRelation } from './models/CharacterRelation';
export type { CharacterSearchCriteria } from './models/CharacterSearchCriteria';
export type { CharacterSpecies } from './models/CharacterSpecies';
export type { ComicCollectionBase } from './models/ComicCollectionBase';
export type { ComicCollectionBaseResponse } from './models/ComicCollectionBaseResponse';
export type { ComicCollectionFull } from './models/ComicCollectionFull';
export type { ComicCollectionFullResponse } from './models/ComicCollectionFullResponse';
export type { ComicCollectionHeader } from './models/ComicCollectionHeader';
export type { ComicCollectionSearchCriteria } from './models/ComicCollectionSearchCriteria';
export type { ComicCollectionV2Full } from './models/ComicCollectionV2Full';
export type { ComicCollectionV2FullResponse } from './models/ComicCollectionV2FullResponse';
export type { ComicsBase } from './models/ComicsBase';
export type { ComicsBaseResponse } from './models/ComicsBaseResponse';
export type { ComicSeriesBase } from './models/ComicSeriesBase';
export type { ComicSeriesBaseResponse } from './models/ComicSeriesBaseResponse';
export type { ComicSeriesFull } from './models/ComicSeriesFull';
export type { ComicSeriesFullResponse } from './models/ComicSeriesFullResponse';
export type { ComicSeriesHeader } from './models/ComicSeriesHeader';
export type { ComicSeriesSearchCriteria } from './models/ComicSeriesSearchCriteria';
export type { ComicsFull } from './models/ComicsFull';
export type { ComicsFullResponse } from './models/ComicsFullResponse';
export type { ComicsHeader } from './models/ComicsHeader';
export type { ComicsSearchCriteria } from './models/ComicsSearchCriteria';
export type { ComicStripBase } from './models/ComicStripBase';
export type { ComicStripBaseResponse } from './models/ComicStripBaseResponse';
export type { ComicStripFull } from './models/ComicStripFull';
export type { ComicStripFullResponse } from './models/ComicStripFullResponse';
export type { ComicStripHeader } from './models/ComicStripHeader';
export type { ComicStripSearchCriteria } from './models/ComicStripSearchCriteria';
export type { CompanyBase } from './models/CompanyBase';
export type { CompanyBaseResponse } from './models/CompanyBaseResponse';
export type { CompanyFull } from './models/CompanyFull';
export type { CompanyFullResponse } from './models/CompanyFullResponse';
export type { CompanyHeader } from './models/CompanyHeader';
export type { CompanyV2Base } from './models/CompanyV2Base';
export type { CompanyV2BaseResponse } from './models/CompanyV2BaseResponse';
export type { CompanyV2Full } from './models/CompanyV2Full';
export type { CompanyV2FullResponse } from './models/CompanyV2FullResponse';
export type { CompanyV2SearchCriteria } from './models/CompanyV2SearchCriteria';
export type { ConflictBase } from './models/ConflictBase';
export type { ConflictBaseResponse } from './models/ConflictBaseResponse';
export type { ConflictFull } from './models/ConflictFull';
export type { ConflictFullResponse } from './models/ConflictFullResponse';
export type { ConflictHeader } from './models/ConflictHeader';
export type { ConflictSearchCriteria } from './models/ConflictSearchCriteria';
export type { ConflictV2Full } from './models/ConflictV2Full';
export type { ConflictV2FullResponse } from './models/ConflictV2FullResponse';
export type { ContentLanguage } from './models/ContentLanguage';
export type { ContentRating } from './models/ContentRating';
export { ContentRatingSystem } from './models/ContentRatingSystem';
export type { Country } from './models/Country';
export type { DataVersion } from './models/DataVersion';
export type { ElementBase } from './models/ElementBase';
export type { ElementBaseResponse } from './models/ElementBaseResponse';
export type { ElementFull } from './models/ElementFull';
export type { ElementFullResponse } from './models/ElementFullResponse';
export type { ElementHeader } from './models/ElementHeader';
export type { ElementV2Base } from './models/ElementV2Base';
export type { ElementV2BaseResponse } from './models/ElementV2BaseResponse';
export type { ElementV2Full } from './models/ElementV2Full';
export type { ElementV2FullResponse } from './models/ElementV2FullResponse';
export type { ElementV2SearchCriteria } from './models/ElementV2SearchCriteria';
export type { EpisodeBase } from './models/EpisodeBase';
export type { EpisodeBaseResponse } from './models/EpisodeBaseResponse';
export type { EpisodeFull } from './models/EpisodeFull';
export type { EpisodeFullResponse } from './models/EpisodeFullResponse';
export type { EpisodeHeader } from './models/EpisodeHeader';
export type { EpisodeSearchCriteria } from './models/EpisodeSearchCriteria';
export type { Error } from './models/Error';
export type { FoodBase } from './models/FoodBase';
export type { FoodBaseResponse } from './models/FoodBaseResponse';
export type { FoodFull } from './models/FoodFull';
export type { FoodFullResponse } from './models/FoodFullResponse';
export type { FoodHeader } from './models/FoodHeader';
export type { FoodSearchCriteria } from './models/FoodSearchCriteria';
export { Gender } from './models/Gender';
export type { Genre } from './models/Genre';
export type { LiteratureBase } from './models/LiteratureBase';
export type { LiteratureBaseResponse } from './models/LiteratureBaseResponse';
export type { LiteratureFull } from './models/LiteratureFull';
export type { LiteratureFullResponse } from './models/LiteratureFullResponse';
export type { LiteratureHeader } from './models/LiteratureHeader';
export type { LiteratureSearchCriteria } from './models/LiteratureSearchCriteria';
export type { LocationBase } from './models/LocationBase';
export type { LocationBaseResponse } from './models/LocationBaseResponse';
export type { LocationFull } from './models/LocationFull';
export type { LocationFullResponse } from './models/LocationFullResponse';
export type { LocationHeader } from './models/LocationHeader';
export type { LocationV2Base } from './models/LocationV2Base';
export type { LocationV2BaseResponse } from './models/LocationV2BaseResponse';
export type { LocationV2Full } from './models/LocationV2Full';
export type { LocationV2FullResponse } from './models/LocationV2FullResponse';
export type { LocationV2SearchCriteria } from './models/LocationV2SearchCriteria';
export type { MagazineBase } from './models/MagazineBase';
export type { MagazineBaseResponse } from './models/MagazineBaseResponse';
export type { MagazineFull } from './models/MagazineFull';
export type { MagazineFullResponse } from './models/MagazineFullResponse';
export type { MagazineHeader } from './models/MagazineHeader';
export type { MagazineSearchCriteria } from './models/MagazineSearchCriteria';
export type { MagazineSeriesBase } from './models/MagazineSeriesBase';
export type { MagazineSeriesBaseResponse } from './models/MagazineSeriesBaseResponse';
export type { MagazineSeriesFull } from './models/MagazineSeriesFull';
export type { MagazineSeriesFullResponse } from './models/MagazineSeriesFullResponse';
export type { MagazineSeriesHeader } from './models/MagazineSeriesHeader';
export type { MagazineSeriesSearchCriteria } from './models/MagazineSeriesSearchCriteria';
export { MaritalStatus } from './models/MaritalStatus';
export type { MaterialBase } from './models/MaterialBase';
export type { MaterialBaseResponse } from './models/MaterialBaseResponse';
export type { MaterialFull } from './models/MaterialFull';
export type { MaterialFullResponse } from './models/MaterialFullResponse';
export type { MaterialHeader } from './models/MaterialHeader';
export type { MaterialSearchCriteria } from './models/MaterialSearchCriteria';
export type { MedicalConditionBase } from './models/MedicalConditionBase';
export type { MedicalConditionBaseResponse } from './models/MedicalConditionBaseResponse';
export type { MedicalConditionFull } from './models/MedicalConditionFull';
export type { MedicalConditionFullResponse } from './models/MedicalConditionFullResponse';
export type { MedicalConditionHeader } from './models/MedicalConditionHeader';
export type { MedicalConditionSearchCriteria } from './models/MedicalConditionSearchCriteria';
export type { MovieBase } from './models/MovieBase';
export type { MovieBaseResponse } from './models/MovieBaseResponse';
export type { MovieFull } from './models/MovieFull';
export type { MovieFullResponse } from './models/MovieFullResponse';
export type { MovieHeader } from './models/MovieHeader';
export type { MovieSearchCriteria } from './models/MovieSearchCriteria';
export type { OccupationBase } from './models/OccupationBase';
export type { OccupationBaseResponse } from './models/OccupationBaseResponse';
export type { OccupationFull } from './models/OccupationFull';
export type { OccupationFullResponse } from './models/OccupationFullResponse';
export type { OccupationHeader } from './models/OccupationHeader';
export type { OccupationV2Base } from './models/OccupationV2Base';
export type { OccupationV2BaseResponse } from './models/OccupationV2BaseResponse';
export type { OccupationV2Full } from './models/OccupationV2Full';
export type { OccupationV2FullResponse } from './models/OccupationV2FullResponse';
export type { OccupationV2SearchCriteria } from './models/OccupationV2SearchCriteria';
export type { OrganizationBase } from './models/OrganizationBase';
export type { OrganizationBaseResponse } from './models/OrganizationBaseResponse';
export type { OrganizationFull } from './models/OrganizationFull';
export type { OrganizationFullResponse } from './models/OrganizationFullResponse';
export type { OrganizationHeader } from './models/OrganizationHeader';
export type { OrganizationSearchCriteria } from './models/OrganizationSearchCriteria';
export type { PerformerBase } from './models/PerformerBase';
export type { PerformerBaseResponse } from './models/PerformerBaseResponse';
export type { PerformerFull } from './models/PerformerFull';
export type { PerformerFullResponse } from './models/PerformerFullResponse';
export type { PerformerHeader } from './models/PerformerHeader';
export type { PerformerV2Base } from './models/PerformerV2Base';
export type { PerformerV2BaseResponse } from './models/PerformerV2BaseResponse';
export type { PerformerV2Full } from './models/PerformerV2Full';
export type { PerformerV2FullResponse } from './models/PerformerV2FullResponse';
export type { PerformerV2SearchCriteria } from './models/PerformerV2SearchCriteria';
export type { Platform } from './models/Platform';
export { ProductionRunUnit } from './models/ProductionRunUnit';
export type { Reference } from './models/Reference';
export { ReferenceType } from './models/ReferenceType';
export type { RequestSort } from './models/RequestSort';
export type { RequestSortClause } from './models/RequestSortClause';
export { RequestSortDirection } from './models/RequestSortDirection';
export type { ResponsePage } from './models/ResponsePage';
export type { ResponseSort } from './models/ResponseSort';
export type { ResponseSortClause } from './models/ResponseSortClause';
export { ResponseSortDirection } from './models/ResponseSortDirection';
export type { SeasonBase } from './models/SeasonBase';
export type { SeasonBaseResponse } from './models/SeasonBaseResponse';
export type { SeasonFull } from './models/SeasonFull';
export type { SeasonFullResponse } from './models/SeasonFullResponse';
export type { SeasonHeader } from './models/SeasonHeader';
export type { SeasonSearchCriteria } from './models/SeasonSearchCriteria';
export type { SeriesBase } from './models/SeriesBase';
export type { SeriesBaseResponse } from './models/SeriesBaseResponse';
export type { SeriesFull } from './models/SeriesFull';
export type { SeriesFullResponse } from './models/SeriesFullResponse';
export type { SeriesHeader } from './models/SeriesHeader';
export type { SeriesSearchCriteria } from './models/SeriesSearchCriteria';
export type { SoundtrackBase } from './models/SoundtrackBase';
export type { SoundtrackBaseResponse } from './models/SoundtrackBaseResponse';
export type { SoundtrackFull } from './models/SoundtrackFull';
export type { SoundtrackFullResponse } from './models/SoundtrackFullResponse';
export type { SoundtrackHeader } from './models/SoundtrackHeader';
export type { SoundtrackSearchCriteria } from './models/SoundtrackSearchCriteria';
export type { SpacecraftBase } from './models/SpacecraftBase';
export type { SpacecraftBaseResponse } from './models/SpacecraftBaseResponse';
export type { SpacecraftClassBase } from './models/SpacecraftClassBase';
export type { SpacecraftClassBaseResponse } from './models/SpacecraftClassBaseResponse';
export type { SpacecraftClassFull } from './models/SpacecraftClassFull';
export type { SpacecraftClassFullResponse } from './models/SpacecraftClassFullResponse';
export type { SpacecraftClassHeader } from './models/SpacecraftClassHeader';
export type { SpacecraftClassV2Base } from './models/SpacecraftClassV2Base';
export type { SpacecraftClassV2BaseResponse } from './models/SpacecraftClassV2BaseResponse';
export type { SpacecraftClassV2Full } from './models/SpacecraftClassV2Full';
export type { SpacecraftClassV2FullResponse } from './models/SpacecraftClassV2FullResponse';
export type { SpacecraftClassV2SearchCriteria } from './models/SpacecraftClassV2SearchCriteria';
export type { SpacecraftClassV3Full } from './models/SpacecraftClassV3Full';
export type { SpacecraftClassV3FullResponse } from './models/SpacecraftClassV3FullResponse';
export type { SpacecraftFull } from './models/SpacecraftFull';
export type { SpacecraftFullResponse } from './models/SpacecraftFullResponse';
export type { SpacecraftHeader } from './models/SpacecraftHeader';
export type { SpacecraftType } from './models/SpacecraftType';
export type { SpacecraftV2Base } from './models/SpacecraftV2Base';
export type { SpacecraftV2BaseResponse } from './models/SpacecraftV2BaseResponse';
export type { SpacecraftV2Full } from './models/SpacecraftV2Full';
export type { SpacecraftV2FullResponse } from './models/SpacecraftV2FullResponse';
export type { SpacecraftV2SearchCriteria } from './models/SpacecraftV2SearchCriteria';
export type { SpeciesBase } from './models/SpeciesBase';
export type { SpeciesBaseResponse } from './models/SpeciesBaseResponse';
export type { SpeciesFull } from './models/SpeciesFull';
export type { SpeciesFullResponse } from './models/SpeciesFullResponse';
export type { SpeciesHeader } from './models/SpeciesHeader';
export type { SpeciesV2Base } from './models/SpeciesV2Base';
export type { SpeciesV2BaseResponse } from './models/SpeciesV2BaseResponse';
export type { SpeciesV2Full } from './models/SpeciesV2Full';
export type { SpeciesV2FullResponse } from './models/SpeciesV2FullResponse';
export type { SpeciesV2SearchCriteria } from './models/SpeciesV2SearchCriteria';
export type { StaffBase } from './models/StaffBase';
export type { StaffBaseResponse } from './models/StaffBaseResponse';
export type { StaffFull } from './models/StaffFull';
export type { StaffFullResponse } from './models/StaffFullResponse';
export type { StaffHeader } from './models/StaffHeader';
export type { StaffV2Base } from './models/StaffV2Base';
export type { StaffV2BaseResponse } from './models/StaffV2BaseResponse';
export type { StaffV2Full } from './models/StaffV2Full';
export type { StaffV2FullResponse } from './models/StaffV2FullResponse';
export type { StaffV2SearchCriteria } from './models/StaffV2SearchCriteria';
export type { TechnologyBase } from './models/TechnologyBase';
export type { TechnologyBaseResponse } from './models/TechnologyBaseResponse';
export type { TechnologyFull } from './models/TechnologyFull';
export type { TechnologyFullResponse } from './models/TechnologyFullResponse';
export type { TechnologyHeader } from './models/TechnologyHeader';
export type { TechnologyV2Base } from './models/TechnologyV2Base';
export type { TechnologyV2BaseResponse } from './models/TechnologyV2BaseResponse';
export type { TechnologyV2Full } from './models/TechnologyV2Full';
export type { TechnologyV2FullResponse } from './models/TechnologyV2FullResponse';
export type { TechnologyV2SearchCriteria } from './models/TechnologyV2SearchCriteria';
export type { TitleBase } from './models/TitleBase';
export type { TitleBaseResponse } from './models/TitleBaseResponse';
export type { TitleFull } from './models/TitleFull';
export type { TitleFullResponse } from './models/TitleFullResponse';
export type { TitleHeader } from './models/TitleHeader';
export type { TitleV2Base } from './models/TitleV2Base';
export type { TitleV2BaseResponse } from './models/TitleV2BaseResponse';
export type { TitleV2Full } from './models/TitleV2Full';
export type { TitleV2FullResponse } from './models/TitleV2FullResponse';
export type { TitleV2SearchCriteria } from './models/TitleV2SearchCriteria';
export type { TradingCardBase } from './models/TradingCardBase';
export type { TradingCardBaseResponse } from './models/TradingCardBaseResponse';
export type { TradingCardDeckBase } from './models/TradingCardDeckBase';
export type { TradingCardDeckBaseResponse } from './models/TradingCardDeckBaseResponse';
export type { TradingCardDeckFull } from './models/TradingCardDeckFull';
export type { TradingCardDeckFullResponse } from './models/TradingCardDeckFullResponse';
export type { TradingCardDeckHeader } from './models/TradingCardDeckHeader';
export type { TradingCardDeckSearchCriteria } from './models/TradingCardDeckSearchCriteria';
export type { TradingCardFull } from './models/TradingCardFull';
export type { TradingCardFullResponse } from './models/TradingCardFullResponse';
export type { TradingCardHeader } from './models/TradingCardHeader';
export type { TradingCardSearchCriteria } from './models/TradingCardSearchCriteria';
export type { TradingCardSetBase } from './models/TradingCardSetBase';
export type { TradingCardSetBaseResponse } from './models/TradingCardSetBaseResponse';
export type { TradingCardSetFull } from './models/TradingCardSetFull';
export type { TradingCardSetFullResponse } from './models/TradingCardSetFullResponse';
export type { TradingCardSetHeader } from './models/TradingCardSetHeader';
export type { TradingCardSetSearchCriteria } from './models/TradingCardSetSearchCriteria';
export type { VideoGameBase } from './models/VideoGameBase';
export type { VideoGameBaseResponse } from './models/VideoGameBaseResponse';
export type { VideoGameFull } from './models/VideoGameFull';
export type { VideoGameFullResponse } from './models/VideoGameFullResponse';
export type { VideoGameHeader } from './models/VideoGameHeader';
export type { VideoGameSearchCriteria } from './models/VideoGameSearchCriteria';
export type { VideoReleaseBase } from './models/VideoReleaseBase';
export type { VideoReleaseBaseResponse } from './models/VideoReleaseBaseResponse';
export { VideoReleaseFormat } from './models/VideoReleaseFormat';
export type { VideoReleaseFull } from './models/VideoReleaseFull';
export type { VideoReleaseFullResponse } from './models/VideoReleaseFullResponse';
export type { VideoReleaseHeader } from './models/VideoReleaseHeader';
export type { VideoReleaseV2Base } from './models/VideoReleaseV2Base';
export type { VideoReleaseV2BaseResponse } from './models/VideoReleaseV2BaseResponse';
export type { VideoReleaseV2Full } from './models/VideoReleaseV2Full';
export type { VideoReleaseV2FullResponse } from './models/VideoReleaseV2FullResponse';
export type { VideoReleaseV2SearchCriteria } from './models/VideoReleaseV2SearchCriteria';
export type { WeaponBase } from './models/WeaponBase';
export type { WeaponBaseResponse } from './models/WeaponBaseResponse';
export type { WeaponFull } from './models/WeaponFull';
export type { WeaponFullResponse } from './models/WeaponFullResponse';
export type { WeaponHeader } from './models/WeaponHeader';
export type { WeaponV2Base } from './models/WeaponV2Base';
export type { WeaponV2BaseResponse } from './models/WeaponV2BaseResponse';
export type { WeaponV2Full } from './models/WeaponV2Full';
export type { WeaponV2FullResponse } from './models/WeaponV2FullResponse';
export type { WeaponV2SearchCriteria } from './models/WeaponV2SearchCriteria';

export { AnimalService } from './services/AnimalService';
export { AstronomicalObjectService } from './services/AstronomicalObjectService';
export { BookService } from './services/BookService';
export { BookCollectionService } from './services/BookCollectionService';
export { BookSeriesService } from './services/BookSeriesService';
export { CharacterService } from './services/CharacterService';
export { ComicCollectionService } from './services/ComicCollectionService';
export { ComicsService } from './services/ComicsService';
export { ComicSeriesService } from './services/ComicSeriesService';
export { ComicStripService } from './services/ComicStripService';
export { CompanyService } from './services/CompanyService';
export { ConflictService } from './services/ConflictService';
export { DataVersionService } from './services/DataVersionService';
export { ElementService } from './services/ElementService';
export { EpisodeService } from './services/EpisodeService';
export { FoodService } from './services/FoodService';
export { LiteratureService } from './services/LiteratureService';
export { LocationService } from './services/LocationService';
export { MagazineService } from './services/MagazineService';
export { MagazineSeriesService } from './services/MagazineSeriesService';
export { MaterialService } from './services/MaterialService';
export { MedicalConditionService } from './services/MedicalConditionService';
export { MovieService } from './services/MovieService';
export { OccupationService } from './services/OccupationService';
export { OrganizationService } from './services/OrganizationService';
export { PerformerService } from './services/PerformerService';
export { SeasonService } from './services/SeasonService';
export { SeriesService } from './services/SeriesService';
export { SoundtrackService } from './services/SoundtrackService';
export { SpacecraftService } from './services/SpacecraftService';
export { SpacecraftClassService } from './services/SpacecraftClassService';
export { SpeciesService } from './services/SpeciesService';
export { StaffService } from './services/StaffService';
export { TechnologyService } from './services/TechnologyService';
export { TitleService } from './services/TitleService';
export { TradingCardService } from './services/TradingCardService';
export { TradingCardDeckService } from './services/TradingCardDeckService';
export { TradingCardSetService } from './services/TradingCardSetService';
export { VideoGameService } from './services/VideoGameService';
export { VideoReleaseService } from './services/VideoReleaseService';
export { WeaponService } from './services/WeaponService';
